allowBuilds:
  '@applemusic-like-lyrics/core': true
  '@applemusic-like-lyrics/lyric': true
  '@applemusic-like-lyrics/vue': true
  '@parcel/watcher': true
  '@swc/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  phantomjs-prebuilt: true
